### ISSUE TITLE
Using square brackets and curly brackets

### ISSUE THREAD

**Issue by Jack10270** [nhanaz-pm-pl/Calculator#2]
Hi first thank you for making this, It is much better than other calculator plugins.
Can you make it so I can use square brackets `[` `]` and curly brackets `{` `}`
So if there are many brackets in the command I can use different brackets to make it more clear like `a + {[b - (c / d)] * 3}`

**Comment by NhanAZ** [comment]
Temp solution: `a + ((b - (c / d))* 3)`

**Comment by NhanAZ** [comment]
I can only solve this by replacing [ ], { } of the input to ( )
The result of the above solution will still be as expected, but if the expression contains an error, the error messages will use ( ) instead of { } and [ ]

**Comment by NhanAZ** [comment]
As mentioned in #3
I think this still should be opened in https://github.com/Muqsit/arithmexp

**Comment by NhanAZ** [comment]
This has been temporarily resolved by https://github.com/nhanaz-pm-pl/Calculator/commit/16bb0619169074936977a343a2cb29c6e8e01b82
Download at: https://poggit.pmmp.io/p/Calculator/0.0.13
You need to set `advancedBrackets` to `true` in `config.yml` to enable this feature

**Comment by NhanAZ** [comment]
I also opened an issue on the library `Muqsit/arithmexp`
You can see here: https://github.com/Muqsit/arithmexp/issues/13

**Comment by Jack10270** [comment]
Thank you !

**Comment by NhanAZ** [comment]
Solved by https://github.com/nhanaz-pm-pl/Calculator/compare/9347610e7223...760e69d38c5f
